from __future__ import annotations

from pathlib import Path
import json

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from ui_style import apply_fa_style, plotly_rtl

DATA_FILE = Path("data/processed/timeuse_person_activity.parquet")
FALLBACK_FILE = Path("data/processed/timeuse_person_activity.pkl.gz")
LABEL_FILE = Path("data/processed/activity_labels.csv")
GEOJSON_FILE = Path("data/geo/iran_provinces_1402.geojson")

DATA_COLUMNS = [
    "pid",
    "survey_year",
    "survey_quarter",
    "ostan",
    "gender",
    "age",
    "activity_status",
    "weight_person",
    "activity_code",
    "minutes",
]

GENDER_OPTIONS = {"همه": None, "مرد": 1, "زن": 2}
EMPLOYMENT_OPTIONS = {"همه": None, "شاغل": 1, "غیرشاغل": 0}
QUARTER_LABELS = {1: "بهار", 2: "تابستان", 3: "پاییز", 4: "زمستان"}

apply_fa_style()


def to_persian_digits(value: object) -> str:
    return str(value).translate(str.maketrans("0123456789.-", "۰۱۲۳۴۵۶۷۸۹٫−"))


@st.cache_resource(show_spinner="در حال بارگذاری داده‌های جغرافیایی...")
def load_activity_data() -> pd.DataFrame:
    if DATA_FILE.exists():
        data = pd.read_parquet(DATA_FILE, columns=DATA_COLUMNS)
    elif FALLBACK_FILE.exists():
        data = pd.read_pickle(FALLBACK_FILE, compression="gzip")
        missing = [column for column in DATA_COLUMNS if column not in data.columns]
        if missing:
            raise KeyError(
                "فایل پردازش‌شده قدیمی است و ستون‌های لازم را ندارد: "
                + ", ".join(missing)
                + ". فایل prepare_data.py جدید را اجرا کنید."
            )
        data = data[DATA_COLUMNS]
    else:
        raise FileNotFoundError(
            "فایل timeuse_person_activity پیدا نشد. ابتدا prepare_data.py را اجرا کنید."
        )

    valid_pid = data["pid"].notna() & data["pid"].astype("string").str.len().gt(0)
    data = data.loc[valid_pid].copy()
    data["pid"] = pd.factorize(data["pid"], sort=False)[0].astype("int32")

    # Normalize province codes without ever converting missing geography to "00".
    # "00" is a genuine province code (Markazi), so empty strings must remain NA.
    province = data["ostan"].astype("string").str.strip()
    province = province.str.replace(r"\.0$", "", regex=True)
    province = province.mask(
        province.isna()
        | province.eq("")
        | province.isin([".", "nan", "None", "<NA>"])
    )
    data["ostan"] = province.str.zfill(2)

    # Compatibility guard for parquet files generated by the earlier buggy
    # prepare_data.py: later-wave missing province values had been turned into
    # "00". If a year contains only "00", treat that year's geography as missing
    # rather than falsely assigning everyone to Markazi.
    for year, group in data.groupby("survey_year", dropna=False):
        codes = set(group["ostan"].dropna().astype(str).unique())
        if codes == {"00"} and pd.notna(year) and int(year) > 1388:
            data.loc[group.index, "ostan"] = pd.NA

    for column in [
        "survey_year",
        "survey_quarter",
        "gender",
        "age",
        "activity_status",
        "weight_person",
        "activity_code",
        "minutes",
    ]:
        data[column] = pd.to_numeric(data[column], errors="coerce")

    data = data.dropna(
        subset=[
            "survey_year",
            "survey_quarter",
            "ostan",
            "gender",
            "age",
            "weight_person",
            "activity_code",
            "minutes",
        ]
    )
    data = data.loc[data["weight_person"].gt(0)]

    # Geographic information is available only for the first Time Use wave.
    # Keep 1387-1388 explicitly and never infer province for later waves.
    data = data.loc[data["survey_year"].isin([1387, 1388])].copy()

    data["survey_year"] = data["survey_year"].astype("int16")
    data["survey_quarter"] = data["survey_quarter"].astype("int8")
    data["gender"] = data["gender"].astype("int8")
    data["age"] = data["age"].astype("int16")
    data["activity_status"] = data["activity_status"].astype("Int16")
    data["activity_code"] = data["activity_code"].astype("int16")
    data["minutes"] = data["minutes"].astype("int16")
    data["weight_person"] = data["weight_person"].astype("float32")
    data["ostan"] = data["ostan"].astype("category")

    return data


@st.cache_data(show_spinner=False)
def load_activity_catalog() -> pd.DataFrame:
    if not LABEL_FILE.exists():
        return pd.DataFrame(
            columns=[
                "activity_code",
                "activity_label",
                "activity_main_label",
                "activity_display",
            ]
        )

    labels = pd.read_csv(LABEL_FILE)
    labels["activity_code"] = pd.to_numeric(
        labels["activity_code"], errors="coerce"
    ).astype("Int16")
    labels = labels.dropna(subset=["activity_code"]).copy()
    labels["activity_code"] = labels["activity_code"].astype("int16")

    if "activity_label" not in labels.columns:
        labels["activity_label"] = labels["activity_code"].map(
            lambda code: f"فعالیت با کد {int(code)}"
        )
    else:
        labels["activity_label"] = labels["activity_label"].fillna(
            labels["activity_code"].map(lambda code: f"فعالیت با کد {int(code)}")
        )

    if "activity_main_label" not in labels.columns:
        labels["activity_main_label"] = "سایر/نامشخص"
    else:
        labels["activity_main_label"] = labels["activity_main_label"].fillna(
            "سایر/نامشخص"
        )

    if "activity_display" not in labels.columns:
        labels["activity_display"] = (
            labels["activity_code"].astype(str)
            + " — "
            + labels["activity_label"].astype(str)
        )

    return labels[
        [
            "activity_code",
            "activity_label",
            "activity_main_label",
            "activity_display",
        ]
    ].drop_duplicates("activity_code")


@st.cache_data(show_spinner=False)
def load_geojson() -> dict:
    if not GEOJSON_FILE.exists():
        raise FileNotFoundError(
            "فایل نقشه data/geo/iran_provinces_1402.geojson پیدا نشد."
        )
    with GEOJSON_FILE.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def build_catalog(data: pd.DataFrame, labels: pd.DataFrame) -> pd.DataFrame:
    present = pd.DataFrame(
        {"activity_code": np.sort(data["activity_code"].dropna().unique())}
    )
    catalog = present.merge(labels, on="activity_code", how="left")
    fallback = catalog["activity_code"].map(
        lambda code: f"فعالیت با کد {int(code)}"
    )
    catalog["activity_label"] = catalog["activity_label"].fillna(fallback)
    catalog["activity_main_label"] = catalog["activity_main_label"].fillna(
        "سایر/نامشخص"
    )
    catalog["activity_display"] = catalog["activity_display"].fillna(
        catalog["activity_code"].astype(str) + " — " + catalog["activity_label"]
    )
    return catalog.sort_values("activity_code").reset_index(drop=True)


def province_name_lookup(geojson: dict) -> dict[str, str]:
    return {
        str(feature["properties"]["ostan"]).zfill(2): feature["properties"][
            "province_name"
        ]
        for feature in geojson["features"]
    }


def calculate_province_metrics(
    base: pd.DataFrame,
    selected_codes: list[int],
    use_weights: bool,
) -> pd.DataFrame:
    persons = base[
        ["pid", "ostan", "weight_person"]
    ].drop_duplicates(["pid", "ostan"])

    selected = base.loc[
        base["activity_code"].isin(selected_codes),
        ["pid", "ostan", "weight_person", "minutes"],
    ]

    person_minutes = (
        selected.groupby(
            ["pid", "ostan", "weight_person"],
            observed=True,
        )["minutes"]
        .sum()
        .reset_index()
    )

    persons = persons.merge(
        person_minutes,
        on=["pid", "ostan", "weight_person"],
        how="left",
    )
    persons["minutes"] = persons["minutes"].fillna(0.0)
    persons["participant"] = persons["minutes"].gt(0).astype("int8")
    persons["analysis_weight"] = (
        persons["weight_person"].astype("float64") if use_weights else 1.0
    )
    persons["weighted_minutes"] = (
        persons["analysis_weight"] * persons["minutes"]
    )
    persons["participant_weight"] = (
        persons["analysis_weight"] * persons["participant"]
    )

    result = (
        persons.groupby("ostan", observed=True)
        .agg(
            population_weight=("analysis_weight", "sum"),
            weighted_minutes=("weighted_minutes", "sum"),
            participant_weight=("participant_weight", "sum"),
            sample_size=("pid", "size"),
            participant_sample=("participant", "sum"),
        )
        .reset_index()
    )

    result["ostan"] = result["ostan"].astype("string").str.zfill(2)
    result["participation_rate"] = np.where(
        result["population_weight"].gt(0),
        100.0 * result["participant_weight"] / result["population_weight"],
        np.nan,
    )
    result["mean_minutes"] = np.where(
        result["population_weight"].gt(0),
        result["weighted_minutes"] / result["population_weight"],
        np.nan,
    )
    return result


def copy_tehran_to_alborz_when_needed(
    result: pd.DataFrame,
    selected_years: list[int],
) -> pd.DataFrame:
    """Match the user's earlier Stata treatment for the pre-Alborz wave."""
    output = result.copy()
    # In 1387-1388 Alborz was not a separate province. If only that wave is
    # selected, show Tehran's estimate for Alborz on the modern 31-province map.
    if set(selected_years).issubset({1387, 1388}) and "30" not in set(output["ostan"]):
        tehran = output.loc[output["ostan"].eq("23")]
        if not tehran.empty:
            alborz = tehran.iloc[[0]].copy()
            alborz["ostan"] = "30"
            output = pd.concat([output, alborz], ignore_index=True)
    return output


def make_map(
    map_data: pd.DataFrame,
    geojson: dict,
    metric: str,
    title: str,
    colorbar_title: str,
    colorscale: str,
    time_unit: str,
) -> go.Figure:
    """
    Draw the full map of Iran for every metric.

    A light base layer contains all 31 province polygons, so the country outline
    and all provincial borders remain visible even when some provinces have no
    observations after filtering. The metric layer is drawn on top only for
    provinces with valid estimates.
    """
    valid = map_data.loc[map_data[metric].notna()].copy()

    figure = go.Figure()

    # Base layer: always draw all 31 provinces.
    figure.add_trace(
        go.Choropleth(
            geojson=geojson,
            featureidkey="properties.ostan",
            locations=map_data["ostan"],
            z=np.zeros(len(map_data), dtype=float),
            colorscale=[
                [0.0, "#F4F6FA"],
                [1.0, "#F4F6FA"],
            ],
            zmin=0,
            zmax=1,
            showscale=False,
            marker_line_color="#111827",
            marker_line_width=1.0,
            hoverinfo="skip",
        )
    )

    # Data layer: color only provinces for which an estimate exists.
    if not valid.empty:
        customdata = np.column_stack(
            [
                valid["province_name"],
                valid["participation_rate"],
                valid["mean_time"],
                valid["sample_size"],
                valid["participant_sample"],
            ]
        )

        if metric == "participation_rate":
            hover_value = "نرخ مشارکت: %{z:.2f}٪"
        else:
            hover_value = f"متوسط زمان: %{{z:.2f}} {time_unit}"

        figure.add_trace(
            go.Choropleth(
                geojson=geojson,
                featureidkey="properties.ostan",
                locations=valid["ostan"],
                z=valid[metric],
                colorscale=colorscale,
                marker_line_color="#111827",
                marker_line_width=1.0,
                customdata=customdata,
                hovertemplate=(
                    "<b>%{customdata[0]}</b>"
                    + "<br>"
                    + hover_value
                    + "<br>نرخ مشارکت: %{customdata[1]:.2f}٪"
                    + f"<br>متوسط زمان: %{{customdata[2]:.2f}} {time_unit}"
                    + "<br>حجم نمونه: %{customdata[3]:,.0f}"
                    + "<br>مشارکت‌کنندگان نمونه: %{customdata[4]:,.0f}"
                    + "<extra></extra>"
                ),
                colorbar=dict(
                    title=dict(
                        text=plotly_rtl(colorbar_title),
                        side="right",
                    ),
                    tickformat=".2f",
                    thickness=18,
                    len=0.72,
                    x=0.98,
                ),
            )
        )

    # IMPORTANT: fit to the entire GeoJSON, not only provinces with data.
    # This guarantees that every figure always shows the whole country.
    figure.update_geos(
        fitbounds="geojson",
        visible=False,
        showcountries=False,
        showcoastlines=False,
        projection_type="mercator",
        bgcolor="white",
    )

    figure.update_layout(
        title=dict(
            text=plotly_rtl(title),
            x=0.5,
            xanchor="center",
            font=dict(size=24),
        ),
        height=700,
        margin=dict(l=15, r=95, t=80, b=15),
        paper_bgcolor="white",
        plot_bgcolor="white",
        font=dict(family="Vazirmatn, Tahoma, Arial", size=14),
    )
    return figure


st.title("توزیع جغرافیایی فعالیت‌ها")
st.caption(
    "توزیع استانی فعالیت‌ها بر پایه موج ۱۳۸۷–۱۳۸۸ طرح گذران وقت. "
    "اطلاعات استان در موج‌های بعدی در فایل یکپارچه موجود نیست."
)

try:
    df = load_activity_data()
    labels = load_activity_catalog()
    geojson = load_geojson()
except (FileNotFoundError, KeyError, ValueError) as exc:
    st.error(str(exc))
    st.stop()

all_years = [1387, 1388]
all_quarters = sorted(int(value) for value in df["survey_quarter"].dropna().unique())

st.info(
    "این صفحه عمداً فقط از موج ۱۳۸۷–۱۳۸۸ استفاده می‌کند؛ "
    "برای موج‌های ۱۳۹۳–۱۳۹۴ و ۱۳۹۸–۱۳۹۹ متغیر استان در داده یکپارچه موجود نیست."
)
age_values = df["age"].dropna()
min_age = int(age_values.min())
max_age = int(age_values.max())

with st.sidebar.form("geo_filters"):
    st.subheader("فیلترهای جامعه مورد بررسی")
    st.markdown("**موج آمارگیری:** ۱۳۸۷–۱۳۸۸")
    selected_years = [1387, 1388]
    selected_quarters = st.multiselect(
        "فصل آمارگیری",
        options=all_quarters,
        default=all_quarters,
        format_func=lambda value: QUARTER_LABELS.get(value, str(value)),
    )
    gender_label = st.selectbox("جنسیت", options=list(GENDER_OPTIONS))
    employment_label = st.selectbox(
        "وضعیت اشتغال", options=list(EMPLOYMENT_OPTIONS)
    )
    age_range = st.slider(
        "دامنه سنی",
        min_value=min_age,
        max_value=max_age,
        value=(min_age, max_age),
    )
    weighting_label = st.radio(
        "روش وزن‌دهی", options=["وزن طرح", "بدون وزن"], index=0
    )
    time_unit = st.radio(
        "واحد زمان", options=["ساعت", "دقیقه"], index=0, horizontal=True
    )
    st.form_submit_button("اعمال فیلترها", width="stretch")

if not selected_quarters:
    st.warning("حداقل یک فصل آمارگیری انتخاب کنید.")
    st.stop()

mask = (
    df["survey_year"].isin(selected_years)
    & df["survey_quarter"].isin(selected_quarters)
    & df["age"].between(age_range[0], age_range[1])
)

selected_gender = GENDER_OPTIONS[gender_label]
if selected_gender is not None:
    mask &= df["gender"].eq(selected_gender)

selected_employment = EMPLOYMENT_OPTIONS[employment_label]
if selected_employment == 1:
    mask &= df["activity_status"].isin([1, 2])
elif selected_employment == 0:
    mask &= df["activity_status"].notna() & ~df["activity_status"].isin([1, 2])

base = df.loc[mask, DATA_COLUMNS]
if base.empty:
    st.warning("برای فیلترهای انتخاب‌شده مشاهده‌ای وجود ندارد.")
    st.stop()

activity_catalog = build_catalog(base, labels)

st.subheader("انتخاب فعالیت")
main_groups = sorted(activity_catalog["activity_main_label"].dropna().unique())
selected_main_groups = st.multiselect(
    "محدودکردن فهرست بر اساس گروه اصلی",
    options=main_groups,
    default=main_groups,
)

code_catalog = activity_catalog.loc[
    activity_catalog["activity_main_label"].isin(selected_main_groups)
]
code_to_display = dict(
    zip(
        code_catalog["activity_code"].astype(int),
        code_catalog["activity_display"],
    )
)
code_options = sorted(code_to_display)
religious_defaults = [code for code in [741, 742, 749] if code in code_options]
default_codes = religious_defaults or code_options[:1]

selected_codes = st.multiselect(
    "کد یا کدهای فعالیت",
    options=code_options,
    default=default_codes,
    format_func=lambda code: code_to_display.get(code, str(code)),
    help="اگر چند کد انتخاب شود، زمان آن‌ها برای هر فرد با هم جمع می‌شود.",
)
if not selected_codes:
    st.info("حداقل یک کد فعالیت انتخاب کنید.")
    st.stop()

use_weights = weighting_label == "وزن طرح"
result = calculate_province_metrics(base, selected_codes, use_weights)
result = copy_tehran_to_alborz_when_needed(result, selected_years)

name_lookup = province_name_lookup(geojson)
result["province_name"] = result["ostan"].map(name_lookup)

divisor = 60.0 if time_unit == "ساعت" else 1.0
result["mean_time"] = result["mean_minutes"] / divisor

# Ensure every map feature is represented so missing provinces are visibly blank.
province_grid = pd.DataFrame(
    {
        "ostan": list(name_lookup.keys()),
        "province_name": list(name_lookup.values()),
    }
)
map_data = province_grid.merge(
    result.drop(columns=["province_name"], errors="ignore"),
    on="ostan",
    how="left",
)

activity_title = (
    code_to_display[selected_codes[0]]
    if len(selected_codes) == 1
    else "مجموع فعالیت‌های انتخاب‌شده"
)

st.markdown(
    f"**فعالیت:** {activity_title}  \n"
    "**موج:** ۱۳۸۷–۱۳۸۸"
)

st.info(
    "در موج ۱۳۸۷–۱۳۸۸، البرز هنوز استان مستقلی نبود. "
    "برای نمایش نقشه ۳۱استانی سال ۱۴۰۲، مطابق کد Stata قبلی، "
    "مقدار تهران برای محدوده البرز نیز نمایش داده می‌شود."
)

participation_map = make_map(
    map_data,
    geojson,
    metric="participation_rate",
    title="نرخ مشارکت در فعالیت منتخب",
    colorbar_title="درصد",
    colorscale="YlGnBu",
    time_unit=time_unit,
)
st.plotly_chart(participation_map, width="stretch")

time_map = make_map(
    map_data,
    geojson,
    metric="mean_time",
    title="متوسط زمان صرف‌شده در فعالیت منتخب",
    colorbar_title=time_unit,
    colorscale="Blues",
    time_unit=time_unit,
)
st.plotly_chart(time_map, width="stretch")

st.subheader("جدول استانی")
table = map_data[
    [
        "province_name",
        "participation_rate",
        "mean_time",
    ]
].copy()
table = table.sort_values("province_name")
st.dataframe(
    table,
    width="stretch",
    hide_index=True,
    column_config={
        "province_name": "استان",
        "participation_rate": st.column_config.NumberColumn(
            "نرخ مشارکت (درصد)", format="%.2f"
        ),
        "mean_time": st.column_config.NumberColumn(
            f"متوسط زمان ({time_unit})", format="%.2f"
        ),
    },
)

export_table = table.rename(
    columns={
        "province_name": "province",
        "participation_rate": "participation_rate_percent",
        "mean_time": f"mean_time_{'hours' if time_unit == 'ساعت' else 'minutes'}",
    }
)
st.download_button(
    "دانلود داده‌های استانی",
    data=export_table.to_csv(index=False, encoding="utf-8-sig").encode("utf-8-sig"),
    file_name="timeuse_province_activity_map.csv",
    mime="text/csv",
    width="stretch",
)
